#!/bin/bash

# ===========================================设置各参数（不需要的可以删掉或者前面加# ）=============================================
# 设置文件下载路径
FLIE_PATH=${FLIE_PATH:-'./'}

#设置argo-token
TOK=${TOK:-'eyJhIjoiMzg2OGEzNjc2ZTkyZmUxMmY0NjM1YTU0ZmNhMDQ0NDMiLCJ0IjoiMTkzNTA0YmYtMjhiZC00ODdjLWE5ZDEtMmM2NGE0NGJhZjQ3IiwicyI6Ik5UVm1ZMk16TmpndFpqbGtaUzAwTkRreExUZ3pPV010TkdWbU1ERmpNR0l6TVdVNSJ9'}

#设置哪吒
NEZHA_SERVER=${NEZHA_SERVER:-'data.seaw.gq'}
NEZHA_KEY=${NEZHA_KEY:-'Yr7KVevuEL1LKWKmQE'}

#哪吒其他默认参数，无需更改
NEZHA_PORT=${NEZHA_PORT:-'443'}
NEZHA_TLS=${NEZHA_TLS:-'1'}
TLS=${NEZHA_TLS:+'--tls'}

# ===========================================设置下载链接（两种平台都要设置，脚本自适应选择下载）=============================================

# 设置x86_64-argo下载地址
 URL_CF=${URL_CF:-'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64'}

# 设置x86_64-NEZHA下载地址
 URL_NEZHA=${URL_NEZHA:-'https://github.com/dsadsadsss/d/releases/download/sd/nezha-amd'}

# 设置x86_64-bot下载地址（必须内置配置的版本,没有的可以到https://huggingface.co/spaces/sadsadewqeqw/wqeee复制空间编译一个）
 URL_BOT=${URL_BOT:-'https://sadsadewqeqw-wqeee.hf.space/kano-yuan'}

# 设置arm-argo下载地址
 URL_CF2=${URL_CF:-'https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64'}

# 设置arm-NEZHA下载地址
 URL_NEZHA2=${URL_NEZHA:-'https://github.com/dsadsadsss/d/releases/download/sd/nezha-arm'}

# 设置arm-bot下载地址（必须内置配置的版本）
 URL_BOT2=${URL_BOT:-'https://sadsadewqeqw-wqeee.hf.space/kano-yuan-arm'}


